### PR TITLE
About page

### PR DESCRIPTION
**Pull request by nawed2611**
## Create About Page
  - Create an about page and route that to App.js
  - Build a responsive design for the UI
  - Add "Meet Our Team" Section
  - Add Basic Hover animations

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Video Screenshot

https://user-images.githubusercontent.com/83456083/147693838-379d77ee-ecd9-4cc4-b314-c8600ac0582e.mp4

### CODE REVIEW

**Comment by aakankshabhende** [comment]
Good work! Can you please share screenshot of mobile view @nawed2611

**Comment by aakankshabhende** [comment]
Fixes #51

**Comment by nawed2611** [comment]
Sure!

https://user-images.githubusercontent.com/83456083/147733806-1c3d7be3-134e-4be2-88f1-1a4457c61364.mp4

**Comment by aakankshabhende** [comment]
Nice now can you just add any graphical pic related to this project on the right side of about section just to fill the empty place there @nawed2611

**Comment by nawed2611** [comment]
I added some sample images!


https://user-images.githubusercontent.com/83456083/147779417-da28f51a-e820-48f3-a1d5-a074602a46c1.mp4

**Comment by aakankshabhende** [comment]
Great work @nawed2611

**Pull request merged**
