### PR TITLE
Added Charts

### PR DESCRIPTION
**Pull request by sanjay270899**
Fixes: #40 

Made `LineChart` and `PieChart` component.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | 
 :--------------------: |
image  |
Updated |
charts_40 |

### CODE REVIEW

**Comment by ashishnagpal2498** [comment]
Can you make it 50% each in a single component. The issue clearly state that divide component horizontally into two halves.

**Comment by sanjay270899** [comment]
@ashishnagpal2498 
image

**Comment by ashishnagpal2498** [comment]
Can you make both of these chart component to 70% and Add some text in 30% div.
Heading should not be inside chart but shown separately. (not a simple header tag)

**Comment by sanjay270899** [comment]
@ashishnagpal2498 
70% means 70vh?
Total height 200vh for both charts?

**Comment by ashishnagpal2498** [comment]
> 
> 
> @ashishnagpal2498
> 70% means 70vh?
> Total height 200vh for both charts?

I am talking about width buddy. Dividing the component horizontally. 70% - chart, 30% - description 7:3 ratio.

**Comment by sanjay270899** [comment]
@ashishnagpal2498 Like this?
image

**Comment by ashishnagpal2498** [comment]
Yes @sanjay270899

**Comment by sanjay270899** [comment]
@ashishnagpal2498 Done.
image

**Comment by sanjay270899** [comment]
@ashishnagpal2498 It was for DWOC. I think by mistake you have added labels for SWOC.

**Pull request merged**
