### PR TITLE
Added proposed CSS

### PR DESCRIPTION
**Pull request by himanshu007-creator**
## Related Issuse or bug
  - #4 

Fixes: #4

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

COLOR SCHEME

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
I am a participant in both <code>DWOC</code> and <code>SWOC</code>. So please add these both tags along with <code>Level</code> tags accordingly

**Comment by ashishnagpal2498** [comment]
1 issue single tag, you decide DWOC or SWOC ?

**Comment by himanshu007-creator** [comment]
> 1 issue single tag, you decide DWOC or SWOC ?

DWOC

**Comment by himanshu007-creator** [comment]
Please add <code>DWOC</code> and <code>Level-2</code> tags . Today is the last day .

**Pull request merged**
