### PR TITLE
New logo concepts

### PR DESCRIPTION
**Pull request by royquilor**
Hi all,

Just wanted to throw in a concept and kept it simple. The style has the slashes, competitive, hectic or frantic. I think it could suit well for a theme with the diagonal lines for the site. Here are two color versions and some explorations with the text.

Concept A - Red, passion, dark
hackstation-a

Concept B - Calm yet still hacky
hackstation-b

The font is from https://www.behance.net/gallery/67884167/Facon-Free-Font

I look forward to your feedback, relates to https://github.com/ashishnagpal2498/hackstation/issues/1

### CODE REVIEW

**Comment by ashishnagpal2498** [comment]
Hi @royquilor , Could you come up with something which matches the requirements mentioned in readme such as reminder, dashboard something like that.

**Comment by royquilor** [comment]
Hi @ashishnagpal2498 

Some simple concepts with reminder = bell icon and dashboard = graph lines

Concept 1: Either have the tick, smooth or sharp graph 
hackstation-2

Concept 2: Bell shape with letter H
hackstation-3

Look forward to any feedback

**Comment by ashishnagpal2498** [comment]
Bell shape H, with Full name below looks good. Black one. Kindly add the Png file for that and all others too.

**Comment by ashishnagpal2498** [comment]
@royquilor Add the png file, so that I can merge this PR.

**Comment by royquilor** [comment]
@ashishnagpal2498 here we go, did two versions with an outline and solid. 

hackstation-icon-outline-text
hackstation-icon-outline
hackstation-icon-solid-text
hackstation-icon-solid

Please could you add this to the readme?
Logo design by Roy Quilor is licensed under CC BY-NC 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc/4.0

If you could add a link to my portfolio, https://www.quilor.com/ that would be great

**Comment by ashishnagpal2498** [comment]
hi @royquilor I have added "Logo by" in readMe. Kindly update your PR with all the new logos. Also if you could add the bell Icon logo with transparent background that would be great.

**Pull request closed without merging**
