### PR TITLE
Add Login Feature

### LINKED ISSUE #38: Login page component
## 🚀 Feature

- Should be responsive 
- Support login credentials ( username and password) + google and github button
- open to innovation.

### PR DESCRIPTION
**Pull request by mandeep168**
## Related Issuse or bug
  - Added a responsive login page with google and github automatic login support.

Fixes: #38

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I test it locally by running the website on localhost. One  need to install firebase which can be install using "npm install firebase" other things are same as previous.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

image
image
Login using google
image
Login using github
image
If the fields are left blank.
image
Mobile View
mobile1

mobile2

### CODE REVIEW

**Comment by aakankshabhende** [comment]
Good work @mandeep168 
Can you please put your github page link here

**Comment by mandeep168** [comment]
Sure. 
https://github.com/mandeep168

**Comment by aakankshabhende** [comment]
> Sure. https://github.com/mandeep168

I meant to put link of the changes you made on your local repository

**Comment by mandeep168** [comment]
> > Sure. https://github.com/mandeep168
> 
> I meant to put link of the changes you made on your local repository

https://github.com/mandeep168/hackstation/tree/LoginPage

**Comment by aakankshabhende** [comment]
Are your changes responsive? @mandeep168

**Comment by mandeep168** [comment]
Yes changes are responsive and I have resolved the conflicts.

**Comment by aakankshabhende** [comment]
Can you please put here the screenshots of mobile view @mandeep168

**Comment by mandeep168** [comment]
@aakankshabhende I have added the screenshots at the end.

**Comment by aakankshabhende** [comment]
@mandeep168 please resolve the conflicts to get PR merged into the main.

**Pull request closed without merging**
