### PR TITLE
Added contributor's table

### PR DESCRIPTION
**Pull request by himanshu007-creator**
## Related Issuse or bug
  - #47

Fixes: #47 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
I am a participant in both <code>DWOC</code> and <code>SWOC</code>. So please add these both tags along with <code>Level</code> tags accordingly

**Comment by ashishnagpal2498** [comment]
What if a new person comes in and contribute to the project ? Check for github plugin. There are many for such thing. Reference -  https://github.com/smaranjitghose/doc2pen#our-valuable-contributors-

**Comment by himanshu007-creator** [comment]
> What if a new person comes in and contribute to the project ? Check for github plugin. There are many for such thing. Reference - https://github.com/smaranjitghose/doc2pen#our-valuable-contributors-

We just need to copy the table item and modify it. It's simple

**Comment by ashishnagpal2498** [comment]
Since there was no such major change to readme. Reducing level to DWOC - level1

**Pull request merged**
