### PR TITLE
MongoDB Backend

### PR DESCRIPTION
**Pull request by nehaparmar99**
## Related Issuse or bug
  -Setup MongoDB backend

Fixes: #41 

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ashishnagpal2498** [comment]
Take pull from backend branch and make changes accordingly. Server and basic setup has already been done.

**Comment by nehaparmar99** [comment]
> Take pull from backend branch and make changes accordingly. Server and basic setup has already been done.

I had pulled the backend branch into my separate branch.You want me to it directly on your backend branch?

**Comment by ashishnagpal2498** [comment]
Okay. I got it. 
Just one more thing. " Have you tested this mongoDB on your local ?
As what I see from your code. Even if mongoDB fails. The server will setup as "connect" is Async.
Make sure that.

**Comment by nehaparmar99** [comment]
> Okay. I got it.
> Just one more thing. " Have you tested this mongoDB on your local ?
> As what I see from your code. Even if mongoDB fails. The server will setup as "connect" is Async.
> Make sure that.

Yes I've tested it with my credentials.It works fine, and with wrong credentials it shows the error.
It it's connected it displays mongoDB connected, and in case there's an error it'll shows the I've used Promise to handle the asyn nature of connect😅

**Comment by nehaparmar99** [comment]
Also, I get points under DWOC only, or can I get under SWOC too?Since I'm participating in both😅

**Comment by ashishnagpal2498** [comment]
Okay. Kool :P . You'll get points only for one and of that which was stated in issue. :) Keep contributing more.

**Pull request merged**
