### PR TITLE
Adds logo file for HackStation

### PR DESCRIPTION
**Pull request by kavita121**

### CODE REVIEW

**Comment by kavita121** [comment]
This pull request is ineligible for hacktoberfest. Please add hacktoberfest-accepted tag to this PR to make it eligible.Please help me out  :)

**Comment by ashishnagpal2498** [comment]
How will I see, what logos you have added? Please share a link in comment section for all the logos you have added.

**Comment by kavita121** [comment]
Hey!! I have added the photoshop file too along with png files so you can see it. I converted the files from .AI to .PSD. Please check it :)

**Comment by kavita121** [comment]
https://drive.google.com/file/d/10nJIVMSazCdm-w41e9iwTm5eqm3vq5-8/view?usp=sharing
https://drive.google.com/file/d/1yIqPCyAzS98tJThgxRWwUMMiEOHHotEz/view?usp=sharing
You can see in these links!!

**Comment by kavita121** [comment]
Please respond. :)

**Pull request merged**
