### PR TITLE
Documentation - CONTRIBUTING AND CODE OF CONDUCT FILE 

### PR DESCRIPTION
**Pull request by akrish4**
## Related Issuse or bug
  - I have opened a issue regarding creation of code of conduct.md and contributing.md file , which is now resolved 

Fixes: #12 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
This is a documentation issue , I have added the code of conduct and contributing file which doesn't need any local test and it is been self-tested by me.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Original       👇

hack1

 ## Updated 👇 

hack2

hack3|

hack4

hack5

hack6

hack7

### CODE REVIEW

**Comment by akrish4** [comment]
Kindly do check and merge it also add the `DWOC` and `Level-2` labels to the PR 
@ashishnagpal2498

**Comment by akrish4** [comment]
> Kindly do check and merge it also add the `DWOC` and `Level-2` labels to the PR
> @ashishnagpal2498

@ashishnagpal2498

**Comment by ashishnagpal2498** [comment]
Please squash your all your commits to a single commit.

**Comment by akrish4** [comment]
@ashishnagpal2498  I am unable to squash it , You will find a option in merging , choose  `squash and merge` , it will merge it and count as a single commit , I am unable to do it now as i edited in github itself

**Pull request merged**
