### PR TITLE
Adding files for logo.

### PR DESCRIPTION
**Pull request by kcclemo**
Your cat Gif in the README inspired this logo. 😉

### CODE REVIEW

**Comment by ashishnagpal2498** [comment]
Provide me the links of images you have added.

**Comment by kcclemo** [comment]
@ashishnagpal2498 Here is the link to my Figma project.
https://www.figma.com/files/project/15878649/Hackstation-Logo

**Comment by ashishnagpal2498** [comment]
I think the link is private. Either make it public or share by some other medium google drive maybe ?

**Comment by kcclemo** [comment]
@ashishnagpal2498
Just added PNG versions of the logo to that same branch.

**Comment by kcclemo** [comment]
@ashishnagpal2498 
OK here are individual links:
https://www.figma.com/file/2vOstuyQW28GSQ8bqjiFlD/Hackstation-Logo-Cat-and-Mouse?node-id=3%3A2
https://www.figma.com/file/Mmhk8lc10v7cqhlye9Pju8/Hackstation-Logo-Full-Text?node-id=5%3A2

**Comment by kcclemo** [comment]
@ashishnagpal2498 
Can do.

Apart from the color, specifically which requirements are not met in this logo?

Backstory: The cat was inspired by the cat Gif you included in your README.

**Comment by kcclemo** [comment]
@ashishnagpal2498 
Understood. So, keywords I should target are "reminders" and any of its synonyms and "dashboard".

Thanks, I'll go back to the drawing board with this.

**Comment by ashishnagpal2498** [comment]
Hey, are you still working on this?

**Comment by kcclemo** [comment]
Yes, but, feel free to review other designs in the process. I'll
submit mine as soon as it's finished.

On 10/9/20, Ashish Nagpal <notifications@github.com> wrote:
> Hey, are you still working on this?
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ashishnagpal2498/hackstation/pull/3#issuecomment-706206716


-- 
-Kirk

**Pull request closed without merging**
